# Generated by Django 5.2.7 on 2026-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculation_type', models.CharField(choices=[('rheology', 'Rheology Analysis'), ('hydraulics', 'Hydraulics'), ('ecd', 'Equivalent Circulating Density'), ('surge_swab', 'Surge & Swab'), ('custom', 'Custom Calculation')], max_length=20)),
                ('parameters', models.JSONField(help_text='Calculation parameters as JSON')),
                ('results', models.JSONField(help_text='Calculation results as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(help_text='Workflow steps as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
