# Generated by Django 5.2.7 on 2026-02-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculations', '0001_initial'),
        ('fluids', '0001_initial'),
        ('users', '0001_initial'),
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='fluid_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fluids.fluidsample'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='wells.well'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
