# Generated by Django 5.2.7 on 2026-02-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluids', '0001_initial'),
        ('users', '0001_initial'),
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidsample',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='fluidsample',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_samples', to='wells.well'),
        ),
        migrations.AddField(
            model_name='fluidmeasurement',
            name='fluid_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='fluids.fluidsample'),
        ),
        migrations.AddField(
            model_name='fluidsample',
            name='fluid_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluids.fluidtype'),
        ),
    ]
