# Generated by Django 5.2.7 on 2026-02-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_number', models.CharField(max_length=50, unique=True)),
                ('operator', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('depth_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_measured', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells_created', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depth_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('depth_end', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hole_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wells.well')),
            ],
        ),
    ]
